### ISSUE TITLE
数据的样本数量与论文实际表述的有差距

### ISSUE THREAD

**Issue by BinchaoPeng** [hzy95/EPIVAN#1]
![image](https://user-images.githubusercontent.com/43957010/137101584-3ab351d7-3df6-4c94-ae16-5222efda7da1.png)
上面的表是论文记录的各细胞系的样本数量。
下面的表的各细胞系的样本数量是通过csv和数据增广脚本得到的。
发现两者存在数量上的差距，请问这是什么原因呢？

**Comment by lhy0322** [comment]
我的理解是在2113pos和42200neg中分别划出了10%作为独立测试集，作者只提供了他的剩下90%的训练集。

**Comment by BinchaoPeng** [comment]
> 我的理解是在2113pos和42200neg中分别划出了10%作为独立测试集，作者只提供了他的剩下90%的训练集。

好的，十分感谢！！！

**Comment by lhy0322** [comment]
> > 我的理解是 4213pos42200neg 中分别提供了 10% 作为独立的测试集，我只剩下了 90% 的训练集。
> 
> 好，非常感谢！！！

直接使用[Data_Augmentation.R](https://github.com/hzy95/EPIVAN/blob/master/data/Data_Augmentation.R)就可以生成全部的训练集（90%）和测试集（10%），包括平衡后的和不平衡的。但是要配置R语言环境和下载很多包。
